import * as React from "react";
import * as Types from "./types";

declare function Hero(props: {
  as?: React.ElementType;
  sectionSettingsLayout?: "Default" | "Reversed";
  mediaImage?: Types.Asset.Image;
  subheadingSettingsSubheadingText?: React.ReactNode;
  subheadingSettingsColourVariant?: "Base" | "Dark";
  subheadingSettingsSubheadingVisibility?: Types.Visibility.VisibilityConditions;
  headingSettingsHeadingText?: React.ReactNode;
  headingSettingsHeadingTag?: Types.Basic.HeadingTag;
  headingSettingsHeadingSpanClass?: Types.Builtin.Text;
  stepCard1SettingsStep1Icon?: Types.Asset.Image;
  stepCard1SettingsStep1Heading?: React.ReactNode;
  stepCard1SettingsStep1DescriptionVisibility?: Types.Visibility.VisibilityConditions;
  stepCard1SettingsStep1Description?: React.ReactNode;
  stepCard2SettingsStep2Icon?: Types.Asset.Image;
  stepCard2SettingsStep2Heading?: React.ReactNode;
  stepCard2SettingsStep2DescriptionVisibility?: Types.Visibility.VisibilityConditions;
  stepCard2SettingsStep2Description?: React.ReactNode;
  descriptionSettingsDescription1Visibility?: Types.Visibility.VisibilityConditions;
  descriptionSettingsDescription1Text?: React.ReactNode;
  descriptionSettingsDescription2Text?: React.ReactNode;
  descriptionSettingsDescription2Visibility?: Types.Visibility.VisibilityConditions;
  buttonSettingsButton1Link?: Types.Basic.Link;
  buttonSettingsButton1Text?: React.ReactNode;
  buttonSettingsButton2Link?: Types.Basic.Link;
  buttonSettingsButton2Text?: React.ReactNode;
  sectionVisibility?: Types.Visibility.VisibilityConditions;
  easyStepsConnnect?: Types.Visibility.VisibilityConditions;
  ctaVisibility?: Types.Visibility.VisibilityConditions;
  textVisibility?: Types.Visibility.VisibilityConditions;
  text?: React.ReactNode;
  stepCard2SettingsStep2RichTextDescriptionVisibility?: Types.Visibility.VisibilityConditions;
  stepCard2SettingsStep2RichTextDescription?: Types.Basic.RichTextChildren;
  stepCard1SettingsStep1RichTextDescriptionVisibility?: Types.Visibility.VisibilityConditions;
  stepCard1SettingsStep1RichTextDescription?: Types.Basic.RichTextChildren;
}): React.JSX.Element;
