import * as React from "react";
import * as Types from "./webflow_modules/types";

declare function Hero(props: {
  buttonSettingsButton1Link?: Types.Basic.Link;
  buttonSettingsButton1Text?: React.ReactNode;
  buttonSettingsButton2Link?: Types.Basic.Link;
  buttonSettingsButton2Text?: React.ReactNode;
  ctaVisibility?: Types.Visibility.VisibilityConditions;
  descriptionSettingsDescription1Text?: React.ReactNode;
  descriptionSettingsDescription1Visibility?: Types.Visibility.VisibilityConditions;
  descriptionSettingsDescription2Text?: React.ReactNode;
  descriptionSettingsDescription2Visibility?: Types.Visibility.VisibilityConditions;
  easyStepsConnnect?: Types.Visibility.VisibilityConditions;
  headingSettingsHeadingSpanClass?: string;
  headingSettingsHeadingTag?: "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
  headingSettingsHeadingText?: React.ReactNode;
  mediaImage?: Types.Asset.Image;
  sectionSettingsLayout?: "Default" | "Reversed";
  sectionVisibility?: Types.Visibility.VisibilityConditions;
  stepCard1SettingsStep1Description?: React.ReactNode;
  stepCard1SettingsStep1DescriptionVisibility?: Types.Visibility.VisibilityConditions;
  stepCard1SettingsStep1Heading?: React.ReactNode;
  stepCard1SettingsStep1Icon?: Types.Asset.Image;
  stepCard1SettingsStep1RichTextDescription?: Types.Basic.RichTextChildren;
  stepCard1SettingsStep1RichTextDescriptionVisibility?: Types.Visibility.VisibilityConditions;
  stepCard2SettingsStep2Description?: React.ReactNode;
  stepCard2SettingsStep2DescriptionVisibility?: Types.Visibility.VisibilityConditions;
  stepCard2SettingsStep2Heading?: React.ReactNode;
  stepCard2SettingsStep2Icon?: Types.Asset.Image;
  stepCard2SettingsStep2RichTextDescription?: Types.Basic.RichTextChildren;
  stepCard2SettingsStep2RichTextDescriptionVisibility?: Types.Visibility.VisibilityConditions;
  subheadingSettingsColourVariant?: "Base" | "Dark";
  subheadingSettingsSubheadingText?: React.ReactNode;
  subheadingSettingsSubheadingVisibility?: Types.Visibility.VisibilityConditions;
  text?: React.ReactNode;
  textVisibility?: Types.Visibility.VisibilityConditions;
}): React.JSX.Element;
